### ISSUE TITLE
Issue with Gulp 4

### ISSUE THREAD

**Issue by sprguillen** [nosir/libphonenumber-country-metadata#2]
CLI version: 2.2.0
Local version: 4.0.2

I get this error

```
AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\undertake
r\lib\set-task.js:10:3)
    at Gulp.task (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\undertaker\lib\task.js
:13:8)
    at _fn (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\gulp-sync\lib\index.js:38:19
)
    at Object.sync (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\gulp-sync\lib\index.
js:62:7)
    at D:\Workspace\Personal\libphonenumber-country-metadata\gulpfile.js:104:52
    at Function.each (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\underscore\undersc
ore.js:188:9)
    at Object.<anonymous> (D:\Workspace\Personal\libphonenumber-country-metadata\gulpfile.js:85:3)
```

I tried downgrading to an older gulp like 3.9.1 but I get this error:

```
const { Math, Object } = primordials;
                         ^

ReferenceError: primordials is not defined
    at fs.js:27:26
    at req_ (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\natives\index.js:143:24)   
    at Object.req [as require] (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\natives\
index.js:55:10)
    at Object.<anonymous> (D:\Workspace\Personal\libphonenumber-country-metadata\node_modules\graceful-fs\f
s.js:1:37)

```
Which according to one source, requires me to downgrade my node which is such a hassle. Is there a workthrough on this issue?

**Comment by fos7er** [comment]
same here
